@userId = 4aa6b5c2-d0f7-4a40-b1c2-96396d7123ab
PUT {{baseUrl}}/users/{{userId}}/change_password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "Id" : "4aa6b5c2-d0f7-4a40-b1c2-96396d7123ab",
    "CurrentPassword" : "pass123",
    "NewPassword" : "pass1234",
    "NewPasswordCopy" : "pass1234"
}