@host=http://localhost:5181

POST {{host}}/auth/register
Content-Type: application/json

{
    "userName": "John",
    "email": "generic@email.ru",
    "password": "pass123",
    "passwordCopy": "pass123"
}