POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "userName": "MarkUserName",
    "FirstName": "Mark",
    "LastName": "Snow",
    "email": "generic3@email.ru",
    "password": "pass123",
    "passwordCopy": "pass123"
}