@host=http://localhost:5181
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YWE2YjVjMi1kMGY3LTRhNDAtYjFjMi05NjM5NmQ3MTIzYWIiLCJuYW1lIjoiSm9obiIsImp0aSI6IjA1ODRmMDQyLTJhZWEtNDRjNi04YmQyLTJlNTNlODlkYmUzNyIsImV4cCI6MTcyMDAxNjQ2NiwiaXNzIjoiTW9uZXlUcmFja2VyIiwiYXVkIjoiTW9uZXlUcmFja2VyIn0.8i9-VLHjX5jLQvx9Xb4agN6dMBJExWcg-jl004cUVFs

POST {{host}}/transactions
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Amount" : 200,
    "CategoryId": "a808bfc6-b1e5-4ce0-b328-6162b69fff2c", 
    "Note" : "justSomeNote",
    "UserId" : "4aa6b5c2-d0f7-4a40-b1c2-96396d7123ab"
}