@host=http://localhost:5181

GET {{host}}/spendings
Content-Type: application/json
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Njk1ODA1OS03YjRmLTRkMTEtOGNhYy1iNzc0OGMyZTA0ZjAiLCJuYW1lIjoiSm9obiIsImp0aSI6ImI2NWViMTcyLWU0MmUtNDQyMy1iOThhLTI1MmMzZDFhNDBiYyIsImV4cCI6MTcxOTU4MzM4MCwiaXNzIjoiTW9uZXlUcmFja2VyIiwiYXVkIjoiTW9uZXlUcmFja2VyIn0.Eaz0g0Wn8fwdVeSYmg94RH6w231AG0hpwn25GNAKfcE